# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacex/api/device/wifi_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spacex/api/device/wifi_config.proto',
  package='SpaceX.API.Device',
  syntax='proto3',
  serialized_options=b'Z\025spacex.com/api/device',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#spacex/api/device/wifi_config.proto\x12\x11SpaceX.API.Device\"\xac\x03\n\nWifiConfig\x12!\n\x0cnetwork_name\x18\x01 \x01(\tR\x0bnetworkName\x12-\n\x12\x61pply_network_name\x18\xe9\x07 \x01(\x08R\x10\x61pplyNetworkName\x12)\n\x10network_password\x18\x02 \x01(\tR\x0fnetworkPassword\x12\x35\n\x16\x61pply_network_password\x18\xea\x07 \x01(\x08R\x14\x61pplyNetworkPassword\x12!\n\x0c\x63ountry_code\x18\x03 \x01(\tR\x0b\x63ountryCode\x12#\n\rwifi_disabled\x18\x04 \x01(\x08R\x0cwifiDisabled\x12/\n\x13\x61pply_wifi_disabled\x18\xeb\x07 \x01(\x08R\x11\x61pplyWifiDisabled\x12\x19\n\x08lan_ipv4\x18\x05 \x01(\tR\x07lanIpv4\x12/\n\x14lan_ipv4_subnet_mask\x18\x06 \x01(\tR\x11lanIpv4SubnetMask\x12%\n\x0esetup_complete\x18\x07 \x01(\x08R\rsetupCompleteB\x17Z\x15spacex.com/api/deviceb\x06proto3'
)




_WIFICONFIG = _descriptor.Descriptor(
  name='WifiConfig',
  full_name='SpaceX.API.Device.WifiConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='network_name', full_name='SpaceX.API.Device.WifiConfig.network_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='networkName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apply_network_name', full_name='SpaceX.API.Device.WifiConfig.apply_network_name', index=1,
      number=1001, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='applyNetworkName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network_password', full_name='SpaceX.API.Device.WifiConfig.network_password', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='networkPassword', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apply_network_password', full_name='SpaceX.API.Device.WifiConfig.apply_network_password', index=3,
      number=1002, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='applyNetworkPassword', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country_code', full_name='SpaceX.API.Device.WifiConfig.country_code', index=4,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='countryCode', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wifi_disabled', full_name='SpaceX.API.Device.WifiConfig.wifi_disabled', index=5,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='wifiDisabled', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apply_wifi_disabled', full_name='SpaceX.API.Device.WifiConfig.apply_wifi_disabled', index=6,
      number=1003, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='applyWifiDisabled', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lan_ipv4', full_name='SpaceX.API.Device.WifiConfig.lan_ipv4', index=7,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='lanIpv4', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lan_ipv4_subnet_mask', full_name='SpaceX.API.Device.WifiConfig.lan_ipv4_subnet_mask', index=8,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='lanIpv4SubnetMask', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='setup_complete', full_name='SpaceX.API.Device.WifiConfig.setup_complete', index=9,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='setupComplete', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=487,
)

DESCRIPTOR.message_types_by_name['WifiConfig'] = _WIFICONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WifiConfig = _reflection.GeneratedProtocolMessageType('WifiConfig', (_message.Message,), {
  'DESCRIPTOR' : _WIFICONFIG,
  '__module__' : 'spacex.api.device.wifi_config_pb2'
  # @@protoc_insertion_point(class_scope:SpaceX.API.Device.WifiConfig)
  })
_sym_db.RegisterMessage(WifiConfig)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
